secret_key = ""
client_id = ""
client_secret = ""
auth_url = "http://accounts.spotify.com/authorize"
token_url = "http://accounts.spotify.com/api/token"
api_base_url = "http://accounts.spotify.com/v1/"
access_token = ""
bearer_token =""
